import 'package:combo_dream11/src/data/model/enums/enum_other.dart';
import 'package:combo_dream11/src/data/model/enums/player_info_enum.dart';
import 'package:combo_dream11/src/data/model/match_entry.dart';

final List<MatchEntry> mockMatchEntries = [
  // --- Existing 6 Entries ---
  MatchEntry(
    id: 'match-001',
    playerId: '101',
    playerName: 'Virat Kohli',
    playerIplTeam: PlayerIplTeam.royalChallengersBangalore.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1988, 11, 5),
    matchDate: DateTime(2025, 04, 5),
    stadium: 'Eden Gardens',
    pitchCondition: 'Batting Pitch',
    runs: 85,
    ballsFaced: 60,
    fours: 10,
    sixes: 2,
    catches: 1,
  ),
  MatchEntry(
    id: 'match-002',
    playerId: '102',
    playerName: 'Jasprit Bumrah',
    playerIplTeam: PlayerIplTeam.mumbaiIndians.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1991, 02, 23),
    matchDate: DateTime(1991, 02, 23), // Match on DOB!
    stadium: 'Wankhede Stadium',
    pitchCondition: 'Bowling Pitch',
    ballsBowled: 24,
    runsConceded: 18,
    wickets: 3,
    bestBowling: '3/18',
    catches: 0,
  ),
  MatchEntry(
    id: 'match-003',
    playerId: '103',
    playerName: 'MS Dhoni',
    playerIplTeam: PlayerIplTeam.chennaiSuperKings.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.wicketKeeper,
    playerDateOfBirth: DateTime(1981, 7, 7),
    matchDate: DateTime(2025, 03, 5), // Root 5, Destiny 8
    stadium: 'Chidambaram Stadium',
    pitchCondition: 'Balanced Pitch',
    runs: 45,
    ballsFaced: 30,
    fours: 3,
    sixes: 2,
    stumpings: 1,
    catches: 1,
  ),
  MatchEntry(
    id: 'match-004',
    playerId: '101',
    playerName: 'Virat Kohli',
    playerIplTeam: PlayerIplTeam.royalChallengersBangalore.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1988, 11, 5),
    matchDate: DateTime(2023, 10, 15), // Root 6, Destiny 5
    stadium: 'Chidambaram Stadium',
    pitchCondition: 'Balanced Pitch',
    runs: 102,
    ballsFaced: 90,
    fours: 8,
    sixes: 1,
    catches: 0,
  ),
  MatchEntry(
    id: 'match-005',
    playerId: '104',
    playerName: 'Ravindra Jadeja',
    playerIplTeam: PlayerIplTeam.chennaiSuperKings.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.allrounder,
    playerDateOfBirth: DateTime(1988, 12, 6),
    matchDate: DateTime(2023, 8, 15), // Root 6, Destiny 3
    stadium: 'Chidambaram Stadium',
    pitchCondition: 'Balanced Pitch',
    runs: 25,
    ballsFaced: 20,
    ballsBowled: 24,
    runsConceded: 22,
    wickets: 1,
    catches: 2,
  ),
  MatchEntry(
    id: 'match-006',
    playerId: '102',
    playerName: 'Jasprit Bumrah',
    playerIplTeam: PlayerIplTeam.mumbaiIndians.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1993, 07, 6),
    matchDate: DateTime(2023, 10, 14), // Root 5, Destiny 4
    stadium: 'Eden Gardens',
    pitchCondition: 'Batting Pitch',
    ballsBowled: 18,
    runsConceded: 30,
    wickets: 0,
  ),

  // --- New 20 Entries ---
  MatchEntry(
    id: 'match-007',
    playerId: '105',
    playerName: 'Rohit Sharma',
    playerIplTeam: PlayerIplTeam.mumbaiIndians.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1987, 4, 30),
    matchDate: DateTime(2024, 05, 12), // Root 3, Destiny 9
    stadium: 'Wankhede Stadium',
    pitchCondition: 'Flat Track',
    runs: 120,
    ballsFaced: 95,
    fours: 15,
    sixes: 4,
    catches: 0,
  ),
  MatchEntry(
    id: 'match-008',
    playerId: '106',
    playerName: 'KL Rahul',
    playerIplTeam: PlayerIplTeam.gujaratTitans.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman, // Can also be WK
    playerDateOfBirth: DateTime(1992, 4, 18),
    matchDate: DateTime(2024, 11, 23), // Root 5, Destiny 6
    stadium: 'M. Chinnaswamy Stadium',
    pitchCondition: 'Good Batting',
    runs: 65,
    ballsFaced: 55,
    fours: 6,
    sixes: 1,
    catches: 1,
  ),
  MatchEntry(
    id: 'match-009',
    playerId: '107',
    playerName: 'Hardik Pandya',
    playerIplTeam: PlayerIplTeam.mumbaiIndians.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.allrounder,
    playerDateOfBirth: DateTime(1993, 10, 11),
    matchDate: DateTime(2024, 06, 28), // Root 1, Destiny 5
    stadium: 'Narendra Modi Stadium',
    pitchCondition: 'Sporting',
    runs: 35,
    ballsFaced: 18,
    fours: 2,
    sixes: 3,
    ballsBowled: 12,
    runsConceded: 15,
    wickets: 2,
  ),
  MatchEntry(
    id: 'match-010',
    playerId: '108',
    playerName: 'Yuzvendra Chahal',
    playerIplTeam: PlayerIplTeam.rajasthanRoyals.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1990, 7, 23),
    matchDate: DateTime(2024, 09, 05), // Root 5, Destiny 3
    stadium: 'Sawai Mansingh Stadium',
    pitchCondition: 'Dry, Spin Friendly',
    ballsBowled: 24,
    runsConceded: 28,
    wickets: 4,
    bestBowling: '4/28',
  ),
  MatchEntry(
    id: 'match-011',
    playerId: '109',
    playerName: 'Rishabh Pant',
    playerIplTeam: PlayerIplTeam.delhiCapitals.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.wicketKeeper,
    playerDateOfBirth: DateTime(1997, 10, 4),
    matchDate: DateTime(2025, 01, 16), // Root 7, Destiny 8
    stadium: 'Arun Jaitley Stadium',
    pitchCondition: 'Slow Turner',
    runs: 55,
    ballsFaced: 40,
    fours: 5,
    sixes: 2,
    stumpings: 2,
    catches: 2,
  ),
  MatchEntry(
    id: 'match-012',
    playerId: '110',
    playerName: 'Mohammed Shami',
    playerIplTeam: PlayerIplTeam.delhiCapitals.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1990, 9, 3),
    matchDate: DateTime(2023, 11, 19), // Root 1, Destiny 8
    stadium: 'Narendra Modi Stadium',
    pitchCondition: 'Good Pace and Bounce',
    ballsBowled: 30,
    runsConceded: 45,
    wickets: 5,
    bestBowling: '5/45',
  ),
  MatchEntry(
    id: 'match-013',
    playerId: '105',
    playerName: 'Rohit Sharma',
    playerIplTeam: PlayerIplTeam.mumbaiIndians.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1987, 4, 30),
    matchDate: DateTime(
      2023,
      10,
      14,
    ), // Root 5, Destiny 4 (Same as Kohli/Bumrah)
    stadium: 'Eden Gardens',
    pitchCondition: 'Batting Pitch',
    runs: 15,
    ballsFaced: 25,
    fours: 2,
    sixes: 0,
    catches: 1, // Lower score example
  ),
  MatchEntry(
    id: 'match-014',
    playerId: '111',
    playerName: 'Shubman Gill',
    playerIplTeam: PlayerIplTeam.royalChallengersBangalore.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1999, 9, 8),
    matchDate: DateTime(2024, 02, 29), // Root 2, Destiny 3 (Leap Year)
    stadium: 'PCA Stadium Mohali',
    pitchCondition: 'Excellent Batting',
    runs: 92,
    ballsFaced: 80,
    fours: 11,
    sixes: 1,
  ),
  MatchEntry(
    id: 'match-015',
    playerId: '112',
    playerName: 'Axar Patel',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.allrounder,
    playerDateOfBirth: DateTime(1994, 1, 20),
    matchDate: DateTime(2024, 04, 05), // Root 5, Destiny 7
    stadium: 'Narendra Modi Stadium',
    pitchCondition: 'Slow',
    runs: 18,
    ballsFaced: 15,
    ballsBowled: 24,
    runsConceded: 19,
    wickets: 3,
    catches: 1,
  ),
  MatchEntry(
    id: 'match-016',
    playerId: '113',
    playerName: 'Kuldeep Yadav',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1994, 12, 14),
    matchDate: DateTime(2024, 08, 08), // Root 8, Destiny 6
    stadium: 'Green Park Stadium',
    pitchCondition: 'Turns Square',
    ballsBowled: 24,
    runsConceded: 25,
    wickets: 3,
    bestBowling: '3/25',
  ),
  MatchEntry(
    id: 'match-017',
    playerId: '114',
    playerName: 'Suryakumar Yadav',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1990, 9, 14),
    matchDate: DateTime(2024, 07, 07), // Root 7, Destiny 3
    stadium: 'Wankhede Stadium',
    pitchCondition: 'True Bounce',
    runs: 78,
    ballsFaced: 35,
    fours: 6,
    sixes: 7, // High SR
  ),
  MatchEntry(
    id: 'match-018',
    playerId: '107',
    playerName: 'Hardik Pandya',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.allrounder,
    playerDateOfBirth: DateTime(1993, 10, 11),
    matchDate: DateTime(2023, 09, 17), // Root 8, Destiny 5
    stadium: 'R Premadasa Stadium',
    pitchCondition: 'Used Pitch',
    runs: 8,
    ballsFaced: 10,
    ballsBowled: 18,
    runsConceded: 28,
    wickets: 0, // Less effective day
  ),
  MatchEntry(
    id: 'match-019',
    playerId: '115',
    playerName: 'Sanju Samson',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.wicketKeeper,
    playerDateOfBirth: DateTime(1994, 11, 11),
    matchDate: DateTime(2024, 05, 05), // Root 5, Destiny 3
    stadium: 'Sawai Mansingh Stadium',
    pitchCondition: 'Good Batting',
    runs: 48,
    ballsFaced: 38,
    fours: 4,
    sixes: 1,
    catches: 3,
  ),
  MatchEntry(
    id: 'match-020',
    playerId: '116',
    playerName: 'Arshdeep Singh',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1999, 2, 5),
    matchDate: DateTime(2024, 10, 23), // Root 5, Destiny 4
    stadium: 'PCA Stadium Mohali',
    pitchCondition: 'Some Help for Seamers',
    ballsBowled: 24,
    runsConceded: 35,
    wickets: 2,
  ),
  MatchEntry(
    id: 'match-021',
    playerId: '111',
    playerName: 'Shubman Gill',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1999, 9, 8),
    matchDate: DateTime(2025, 03, 05), // Root 5, Destiny 8 (Same as Dhoni)
    stadium: 'Chidambaram Stadium',
    pitchCondition: 'Balanced Pitch',
    runs: 5,
    ballsFaced: 12,
    fours: 1, // Early dismissal
  ),
  MatchEntry(
    id: 'match-022',
    playerId: '109',
    playerName: 'Rishabh Pant',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.wicketKeeper,
    playerDateOfBirth: DateTime(1997, 10, 4),
    matchDate: DateTime(2024, 04, 05), // Root 5, Destiny 7 (Same as Axar)
    stadium: 'Narendra Modi Stadium',
    pitchCondition: 'Slow',
    runs: 22,
    ballsFaced: 25,
    stumpings: 0,
    catches: 1,
  ),
  MatchEntry(
    id: 'match-023',
    playerId: '108',
    playerName: 'Yuzvendra Chahal',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1990, 7, 23),
    matchDate: DateTime(2023, 8, 15), // Root 6, Destiny 3 (Same as Jadeja)
    stadium: 'Chidambaram Stadium',
    pitchCondition: 'Balanced Pitch',
    ballsBowled: 18,
    runsConceded: 33,
    wickets: 1,
  ),
  MatchEntry(
    id: 'match-024',
    playerId: '110',
    playerName: 'Mohammed Shami',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.bowler,
    playerDateOfBirth: DateTime(1990, 9, 3),
    matchDate: DateTime(2025, 01, 16), // Root 7, Destiny 8 (Same as Pant)
    stadium: 'Arun Jaitley Stadium',
    pitchCondition: 'Slow Turner',
    ballsBowled: 24,
    runsConceded: 20,
    wickets: 2,
  ),
  MatchEntry(
    id: 'match-025',
    playerId: '104',
    playerName: 'Ravindra Jadeja',
    playerIplTeam: "",
    playerNationalTeam: "",
    playerRole: PlayerRole.allrounder,
    playerDateOfBirth: DateTime(1988, 12, 6),
    matchDate: DateTime(2024, 07, 07), // Root 7, Destiny 3 (Same as SKY)
    stadium: 'Wankhede Stadium',
    pitchCondition: 'True Bounce',
    runs: 12,
    ballsFaced: 8,
    ballsBowled: 12,
    runsConceded: 10,
    wickets: 0,
  ),
  MatchEntry(
    id: 'match-026',
    playerId: '114',
    playerName: 'Suryakumar Yadav',
    playerIplTeam: PlayerIplTeam.rajasthanRoyals.name,
    playerNationalTeam: "",
    playerRole: PlayerRole.batsman,
    playerDateOfBirth: DateTime(1990, 9, 14),
    matchDate: DateTime(2023, 11, 19), // Root 1, Destiny 8 (Same as Shami)
    stadium: 'Narendra Modi Stadium',
    pitchCondition: 'Good Pace and Bounce',
    runs: 18,
    ballsFaced: 20,
    fours: 2,
  ),
];
